Wrote initial code to support Loki autodetect.  No testing due to lac…
UbiquityRobotics/bus_loki pull request #2
Opened 2018-01-15 14:46 UTC by waynegramlich

…k of Loki.

2018-01-15 15:11 UTC, rohbotics requested changes
Minor issue with the error response.

2018-01-15 15:11 UTC, rohbotics commented on rev_f/bus_server/bus_server.cpp
> +      };
The error response should be 
`0x7E 0x3D 0x31 0x00 0x00 0x00 0x91`

2018-01-15 15:47 UTC, waynegramlich commented
I updated the code and did another pull request.

2018-01-15 15:48 UTC, waynegramlich commented
I updated the code and generated a new pull request.

2018-01-15 15:49 UTC, rohbotics commented
Don't open a new PR, when you push to the branch it gets included into this PR.

2018-01-15 15:55 UTC, waynegramlich commented
Sorry, 'bout that.  The github documentation on pull requests is pretty weak.

2018-01-15 17:15 UTC, rohbotics approved these changes
The protocol stuff looks good now.

2018-01-18 04:20 UTC, rohbotics requested changes
Found a bug

2018-01-18 04:20 UTC, rohbotics commented on rev_f/bus_server/bus_server.cpp
> +	0x3b,   // Register read response
Response should be 0x3C

2026-01-07 22:04 UTC, merged